version: "1"

services:
  postgres_master:
    container_name: postgres_master
    image: postgres:14.5
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "past1901"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./data-slave:/var/lib/postgresql/data-slave
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-script:/etc/postgresql/init-script
      - ./data_example:/var/lib/postgresql/data_example
      - ./createdb_stores.sql:/docker-entrypoint-initdb.d/createdb_stores.sql
      - ./createdb_view.sql:/docker-entrypoint-initdb.d/createdb_view.sql
      - ./view_gmv.sql:/docker-entrypoint-initdb.d/view_gmv.sql
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

  postgres_slave:
    container_name: postgres_slave
    image: postgres:14.5
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "past1901"
    volumes:
      - ./data-slave:/var/lib/postgresql/data
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "127.0.0.1:5433:5432"
    restart: always

  metabase:
    container_name: metabase
    image: metabase/metabase
    ports:
      -  "127.0.0.1:3000:3000"
    restart: always
    